# <----- Session-2 ----->

In [1]:
import numpy as np

Task.1 :- Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.


In [5]:
rating = np.array([[4.5,5.0,3.5,4.5,4.4],[3.5,4.5,5.0,4.0,3.0],[3.0,4.0,5.0,4.5,3.5],[2.5,1.5,1,2,3]])
rating[1:3]


array([[3.5, 4.5, 5. , 4. , 3. ],
       [3. , 4. , 5. , 4.5, 3.5]])

Task.2 :- Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>

In [7]:
steps = np.array([7500,8200,9000,9500,10000,6500,6000,8100,8000,9900,11000])
a = np.array([steps > 8000])
a

array([[False,  True,  True,  True,  True, False, False,  True, False,
         True,  True]])

Task.3 :- Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.


In [8]:
GT = np.array([180,190,200,250,165,175,199,201])
GT[[1,4,6]]

array([190, 165, 199])

Task.4 :-Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>


In [14]:
price = np.array([1000,2000,3000])
b = price*0.9
b

array([ 900., 1800., 2700.])

Task.5 :-Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.


In [23]:
song = np.array([1,2,3,4,5,0,-1,-2,-3,-4])
song[song < 0] = 0
song


array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])