# <--------- Session-3 --------->

In [2]:
import numpy as np

Task.1:- Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.



In [3]:
arr1 = np.array([[1,2],[2,3]])
arr2 = np.array([[3,4],[4,3]])

In [4]:
arr1 + arr2

array([[4, 6],
       [6, 6]])

In [5]:
arr2 - arr1

array([[2, 2],
       [2, 0]])

In [6]:
arr1 * arr2

array([[3, 8],
       [8, 9]])

In [7]:
arr1/arr2

array([[0.33333333, 0.5       ],
       [0.5       , 1.        ]])

Task.2 :- Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.
 

In [18]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
c = np.matrix(a)
d = np.matrix(b)

In [19]:
c,d

(matrix([[7, 2, 8],
         [3, 4, 8],
         [1, 3, 2]], dtype=int32),
 matrix([[6, 3, 3],
         [9, 8, 6],
         [8, 4, 6]], dtype=int32))

In [23]:
np.dot(c,d)

matrix([[124,  69,  81],
        [118,  73,  81],
        [ 49,  35,  33]], dtype=int32)

In [21]:
np.matmul(c,d)

matrix([[124,  69,  81],
        [118,  73,  81],
        [ 49,  35,  33]], dtype=int32)

Task.3 :- Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.


In [35]:
a = np.random.randint(1000,1024,(4,4))
b = np.matrix(a)
b

matrix([[1011, 1010, 1017, 1017],
        [1013, 1014, 1001, 1017],
        [1014, 1012, 1002, 1013],
        [1005, 1018, 1007, 1001]], dtype=int32)

In [36]:
c = b.T
c

matrix([[1011, 1013, 1014, 1005],
        [1010, 1014, 1012, 1018],
        [1017, 1001, 1002, 1007],
        [1017, 1017, 1013, 1001]], dtype=int32)

In [37]:
np.mean(c)

np.float64(1010.75)

In [38]:
np.median(c)

matrix([[1001., 1001., 1007., 1005., 1010., 1002., 1011., 1012., 1013.,
         1013., 1014., 1017., 1017., 1017., 1014., 1018.]])

In [40]:
np.std(c)

np.float64(5.6844085004510365)

In [41]:
np.var(c)

np.float64(32.3125)

Task.4 :- Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>


In [43]:
a = np.random.randint(1,6,(3,3))
b = np.matrix(a)
b

matrix([[4, 3, 3],
        [5, 5, 2],
        [2, 1, 2]], dtype=int32)

In [44]:
np.linalg.inv(b)

matrix([[-8.,  3.,  9.],
        [ 6., -2., -7.],
        [ 5., -2., -5.]])

In [45]:
np.linalg.det(b)

np.float64(-1.0000000000000009)

In [47]:
np.linalg.eig(b)

EigResult(eigenvalues=array([ 9.39146764, -0.06367605,  1.67220842]), eigenvectors=matrix([[-0.57611753, -0.7203107 ,  0.30069512],
        [-0.77467868,  0.53861676, -0.78087447],
        [-0.26069434,  0.43708635,  0.54755595]]))

Task.5 :- Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.


In [49]:
a = np.random.randint(1,10,(2,6))
a

array([[3, 5, 6, 5, 2, 5],
       [6, 8, 5, 6, 8, 2]], dtype=int32)

In [50]:
a.reshape(3,4)

array([[3, 5, 6, 5],
       [2, 5, 6, 8],
       [5, 6, 8, 2]], dtype=int32)

In [52]:
b = np.split(a,2)
b

[array([[3, 5, 6, 5, 2, 5]], dtype=int32),
 array([[6, 8, 5, 6, 8, 2]], dtype=int32)]

In [53]:
np.stack(b)

array([[[3, 5, 6, 5, 2, 5]],

       [[6, 8, 5, 6, 8, 2]]], dtype=int32)