# <---------- Session-1 ---------->

Task.1 :- Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.


In [1]:
# Already! Done in class

In [2]:
import numpy as np

Task.2:- Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.


In [10]:
followers = np.array([1200, 15000, 67000, 340000, 1250000])

print("array :",followers)
print("Shape :",np.shape(followers))
print("Dimensions :",np.ndim(followers))
print("datatype:",followers.dtype)

array : [   1200   15000   67000  340000 1250000]
Shape : (5,)
Dimensions : 1
datatype: int64


Task.3 :- Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.

In [23]:
zomato = np.arange(101,111)
zomato


array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [25]:
zomato.size

10

Task.4 :-   Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment.


In [27]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
b = np.matrix(a)
b

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [32]:
print(a.diagonal())
print(b.diagonal())

# diagonal values = 1 represents the matrix or array is Identity


[1. 1. 1.]
[[1. 1. 1.]]


Task.5 :- Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong> Use np.array() for conversion and .itemsize for memory size.</em>


In [34]:
list = [45, 67, 120, 89, 54]

scores = np.array(list)
scores

array([ 45,  67, 120,  89,  54])

In [38]:
scores.itemsize

8